name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Dependências
        run: npm install

      - name: Build do Projeto Web (Vite)
        run: npm run build

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "21"

      - name: Sincronizar Capacitor
        run: |
          npx cap sync android

      - name: Dar permissão ao Gradle
        run: chmod +x android/gradlew

      - name: Construir APK (Debug)
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: agenday-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
